
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author SARSSXD
 */
public class EditNilai extends javax.swing.JFrame {

    /**
     * Creates new form EditMapel
     */
    public EditNilai() {
        initComponents();
        tampil_database();
        isiComboBoxNISN();
        tampil_textField();
    }

    private ResultSet hasil;
    private ResultSet hasil1;
    private ResultSet hasil2;

    CrudNilai aa = new CrudNilai();
    CrudSantri bb = new CrudSantri();
    CrudMatpel cc = new CrudMatpel();
    CrudUstad dd = new CrudUstad();

    public void isiComboBoxNISN() {
        try {
            CrudSantri crudSantri = new CrudSantri();
            ResultSet hasilSantri = crudSantri.tampilData();

            CrudUstad crudUstad = new CrudUstad();
            ResultSet hasilUstad = crudUstad.tampilData();

            CrudMatpel crudMatpel = new CrudMatpel();
            ResultSet hasilMatpel = crudMatpel.tampilDataMatpel();

            while (hasilSantri.next() && hasilUstad.next() && hasilMatpel.next()) {
                String nisn = hasilSantri.getString("NISN");
                String id_ustad = hasilUstad.getString("id_ustad");
                String id_matpel = hasilMatpel.getString("id_matpel");

                jComboBox_NISN.addItem(nisn);
                jComboBox_id_ustad.addItem(id_ustad);
                jComboBox_id_mapel.addItem(id_matpel);

            }

            // Tutup koneksi setelah selesai menggunakan ResultSet
            hasilSantri.close();
            hasilUstad.close();
            hasilMatpel.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void reset_text() {
        txt_nilai.setText("");
        txt_UTS.setText("");
        txt_UAS.setText("");
    }

    public void tampil_database() {
        Object[] baris = {"ID Nilai", "NISN", "ID Mapel", "ID Ustad", "UAS", "UTS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, baris);
        table_nilai.setModel(tabmode);
        try {
            hasil = aa.tampilData();
            while (hasil.next()) {
                //id_nilai, NISN, id_matpel, id_ustad, UAS, UTS
                String id_nilai = hasil.getString("id_nilai");
                String nisn = hasil.getString("NISN");
                String idMatpel = hasil.getString("id_matpel");
                String idUstad = hasil.getString("id_ustad");
                String uas = hasil.getString("UAS");
                String uts = hasil.getString("UTS");
                String[] data = {id_nilai, nisn, idMatpel, idUstad, uas, uts};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void tampil_textField() {
        try {
            int idMatpel = Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex()));
            int idUstad = Integer.parseInt(jComboBox_id_ustad.getItemAt(jComboBox_id_ustad.getSelectedIndex()));
            String nisn = jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex());

            hasil = cc.CariData(idMatpel);
            hasil1 = bb.CariData(nisn);
            hasil2 = dd.CariData(idUstad);

            if (hasil1.next()) {
                String santri = hasil1.getString("Nama");
                txt_santri.setText(santri);
            }
            if (hasil.next()) {
                String Matpel = hasil.getString("nama_matpel");
                txt_Matpel.setText(Matpel);
            }
            if (hasil2.next()) {
                String ustad = hasil2.getString("nama_ustad");
                txt_ustad.setText(ustad);
            }
        } catch (SQLException | NumberFormatException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nilai = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_nilai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Matpel = new javax.swing.JTextField();
        txt_ustad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        txt_pencarian = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        txt_santri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_UTS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_UAS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_id_mapel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_id_ustad = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox_NISN = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aplikasi Pendataan Matpel");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 70, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_nilai);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 12, -1, 418));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Aplikasi Pendataan Nilai");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 12, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Nilai");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 185, -1, -1));
        jPanel1.add(txt_nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 183, 235, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mata Pelajaran");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 222, -1, -1));
        jPanel1.add(txt_Matpel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 220, 235, -1));
        jPanel1.add(txt_ustad, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 257, 235, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Ustad");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 259, -1, -1));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 405, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 405, -1, -1));

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 405, -1, -1));

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 405, -1, -1));

        txt_pencarian.setText("....................................... ISI ID NILAI ........................................");
        txt_pencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pencarianMouseClicked(evt);
            }
        });
        txt_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pencarianActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 451, -1, -1));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 448, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 448, -1, -1));
        jPanel1.add(txt_santri, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 294, 235, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nama Santri");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 296, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nilai UTS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 333, -1, -1));
        jPanel1.add(txt_UTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 331, 235, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nilai UAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 370, -1, -1));
        jPanel1.add(txt_UAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 368, 235, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ID Mapel");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 146, -1, -1));

        jComboBox_id_mapel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_id_mapelItemStateChanged(evt);
            }
        });
        jComboBox_id_mapel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jComboBox_id_mapelMouseMoved(evt);
            }
        });
        jComboBox_id_mapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox_id_mapelMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox_id_mapelMouseReleased(evt);
            }
        });
        jComboBox_id_mapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_id_mapelActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_id_mapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 141, 235, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Ustad");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, -1, -1));

        jComboBox_id_ustad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_id_ustadItemStateChanged(evt);
            }
        });
        jComboBox_id_ustad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_id_ustadActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_id_ustad, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 99, 235, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NISN");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 62, -1, -1));

        jComboBox_NISN.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_NISNItemStateChanged(evt);
            }
        });
        jComboBox_NISN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NISNActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox_NISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 57, 235, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/katerina-a.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        dispose();
        Home home = new Home();
        home.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void txt_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pencarianActionPerformed
        txt_pencarian.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pencarianActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if (txt_nilai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_nilai.requestFocus();
        } else if (txt_UTS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UTS belum diisi !");
            txt_UTS.requestFocus();
        } else if (txt_UAS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UAS belum diisi !");
            txt_UAS.requestFocus();
        } else {
            try {
                aa.setId_nilai(Integer.parseInt(txt_nilai.getText()));
                aa.setNISN(Integer.parseInt(jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex())));
                aa.setId_matpel(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
                aa.setId_ustad(Integer.parseInt(jComboBox_id_ustad.getItemAt(jComboBox_id_ustad.getSelectedIndex())));
                aa.setUTS(Integer.parseInt(txt_UTS.getText()));
                aa.setUAS(Integer.parseInt(txt_UAS.getText()));
                aa.simpanData(aa.getId_nilai(), aa.getNISN(), aa.getId_matpel(), aa.getId_ustad(), aa.getUAS(), aa.getUTS());
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        if (txt_nilai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_nilai.requestFocus();
        } else if (txt_UTS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UTS belum diisi !");
            txt_UTS.requestFocus();
        } else if (txt_UAS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UAS belum diisi !");
            txt_UAS.requestFocus();
        } else {
            try {
                aa.setId_nilai(Integer.parseInt(txt_nilai.getText()));
                aa.setNISN(Integer.parseInt(jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex())));
                aa.setId_matpel(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
                aa.setId_ustad(Integer.parseInt(jComboBox_id_ustad.getItemAt(jComboBox_id_ustad.getSelectedIndex())));
                aa.setUTS(Integer.parseInt(txt_UTS.getText()));
                aa.setUAS(Integer.parseInt(txt_UAS.getText()));
                aa.ubahData(aa.getId_nilai(), aa.getNISN(), aa.getId_matpel(), aa.getId_ustad(), aa.getUAS(), aa.getUTS());
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tampil_database();
        reset_text();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    private void txt_pencarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pencarianMouseClicked
        txt_pencarian.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pencarianMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if (txt_pencarian.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_pencarian.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?", "Warning", 2) == JOptionPane.YES_OPTION) {
                String nisn = "";
                try {
                    aa.setId_nilai(Integer.parseInt(txt_pencarian.getText()));
                    aa.hapusData(aa.getId_nilai());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String id_nilai = txt_pencarian.getText();
        Object[] baris = {"ID Nilai", "NISN", "ID Mapel", "ID Ustad", "UAS", "UTS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, baris);
        table_nilai.setModel(tabmode);

        try {
            hasil = aa.CariData(Integer.parseInt(id_nilai));
            if (hasil.next()) {
                String id = hasil.getString("id_nilai");
                String nisn = hasil.getString("NISN");
                String idMatpel = hasil.getString("id_matpel");
                String idUstad = hasil.getString("id_ustad");
                String uas = hasil.getString("UAS");
                String uts = hasil.getString("UTS");
                String[] data = {id, nisn, idMatpel, idUstad, uas, uts};
                tabmode.addRow(data);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void jComboBox_id_mapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_id_mapelActionPerformed
    }//GEN-LAST:event_jComboBox_id_mapelActionPerformed

    private void jComboBox_id_ustadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_id_ustadActionPerformed
    }//GEN-LAST:event_jComboBox_id_ustadActionPerformed

    private void jComboBox_NISNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NISNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NISNActionPerformed

    private void jComboBox_id_mapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_id_mapelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_id_mapelMouseClicked

    private void jComboBox_id_mapelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_id_mapelMouseReleased

    }//GEN-LAST:event_jComboBox_id_mapelMouseReleased

    private void jComboBox_id_mapelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox_id_mapelMouseMoved

    }//GEN-LAST:event_jComboBox_id_mapelMouseMoved

    private void jComboBox_id_mapelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_id_mapelItemStateChanged
        tampil_textField();
    }//GEN-LAST:event_jComboBox_id_mapelItemStateChanged

    private void jComboBox_id_ustadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_id_ustadItemStateChanged
        tampil_textField();    }//GEN-LAST:event_jComboBox_id_ustadItemStateChanged

    private void jComboBox_NISNItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_NISNItemStateChanged
        tampil_textField();        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NISNItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMapel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> jComboBox_NISN;
    private javax.swing.JComboBox<String> jComboBox_id_mapel;
    private javax.swing.JComboBox<String> jComboBox_id_ustad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_nilai;
    private javax.swing.JTextField txt_Matpel;
    private javax.swing.JTextField txt_UAS;
    private javax.swing.JTextField txt_UTS;
    private javax.swing.JTextField txt_nilai;
    private javax.swing.JTextField txt_pencarian;
    private javax.swing.JTextField txt_santri;
    private javax.swing.JTextField txt_ustad;
    // End of variables declaration//GEN-END:variables
}
