package prak_pbo_projek;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SARSSXD
 */
public class EditNilai extends javax.swing.JFrame {

    /**
     * Creates new form EditNilai
     */
    public EditNilai() {
        initComponents();
        tampil_database();
        isiComboBoxNISN();
        tampil_textField();
    }

    private ResultSet hasil;
    private ResultSet hasil1;
    private ResultSet hasil2;

    CrudNilai aa = new CrudNilai();
    CrudSantri bb = new CrudSantri();
    CrudMatpel cc = new CrudMatpel();
    CrudUstad dd = new CrudUstad();

    public void isiComboBoxNISN() {
        try {
            CrudSantri crudSantri = new CrudSantri();
            ResultSet hasilSantri = crudSantri.tampilData();

            CrudUstad crudUstad = new CrudUstad();
            ResultSet hasilUstad = crudUstad.tampilData();

            CrudMatpel crudMatpel = new CrudMatpel();
            ResultSet hasilMatpel = crudMatpel.tampilDataMatpel();

            while (hasilSantri.next() && hasilUstad.next() && hasilMatpel.next()) {
                String nisn = hasilSantri.getString("NISN");
                String id_ustad = hasilUstad.getString("id_ustad");
                String id_matpel = hasilMatpel.getString("id_matpel");

                jComboBox_NISN.addItem(nisn);
                jComboBox_id_ustad.addItem(id_ustad);
                jComboBox_id_mapel.addItem(id_matpel);

            }

            // Tutup koneksi setelah selesai menggunakan ResultSet
            hasilSantri.close();
            hasilUstad.close();
            hasilMatpel.close();

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void reset_text() {
        txt_nilai.setText("");
        txt_UTS.setText("");
        txt_UAS.setText("");
    }

    public void tampil_database() {
        Object[] baris = {"ID Nilai", "NISN", "ID Mapel", "ID Ustad", "UAS", "UTS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, baris);
        table_nilai.setModel(tabmode);
        jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex());
        try {
            hasil = aa.tampilData();
            while (hasil.next()) {
                //id_nilai, NISN, id_matpel, id_ustad, UAS, UTS
                String id_nilai = hasil.getString("id_nilai");
                String nisn = hasil.getString("NISN");
                String idMatpel = hasil.getString("id_matpel");
                String idUstad = hasil.getString("id_ustad");
                String uas = hasil.getString("UAS");
                String uts = hasil.getString("UTS");
                String[] data = {id_nilai, nisn, idMatpel, idUstad, uas, uts};
                tabmode.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public void tampil_textField() {
        try {
            hasil = cc.CariData(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
            hasil1 = bb.CariData(jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex()));
            hasil2 = dd.CariData(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
            if (hasil1.next()) {
                String santri = hasil1.getString("Nama");
                txt_Matpel.setText(santri);
            }
            if (hasil.next()) {
                String Matpel = hasil.getString("nama_matpel");
                txt_Matpel.setText(Matpel);
            }
            if (hasil2.next()) {
                String ustad = hasil2.getString("nama_ustad");
                txt_ustad.setText(ustad);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_santri = new javax.swing.JTextField();
        txt_ustad = new javax.swing.JTextField();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_UTS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_UAS = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_Matpel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_NISN = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_id_ustad = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_nilai = new javax.swing.JTable();
        txt_pencarian = new javax.swing.JTextField();
        btn_Hapus = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        jComboBox_id_mapel = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txt_nilai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 70, 70));

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_home.setText("Home");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aplikasi Pendataan Santri");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Ustad");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Santri");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nilai UTS");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nilai UAS");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mata Pelajaran");

        txt_Matpel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MatpelActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NISN");

        jComboBox_NISN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_NISNActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Ustad");

        table_nilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_nilai);

        txt_pencarian.setText("...............................................ISI apaini .........................................");
        txt_pencarian.setToolTipText("");
        txt_pencarian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_pencarianMouseClicked(evt);
            }
        });
        txt_pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pencarianActionPerformed(evt);
            }
        });

        btn_Hapus.setText("Hapus");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ID Mapel");

        txt_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nilaiActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID Nilai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_tambah)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_reset)
                        .addGap(18, 18, 18)
                        .addComponent(btn_home))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_NISN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_id_ustad, 0, 220, Short.MAX_VALUE)
                            .addComponent(jComboBox_id_mapel, 0, 220, Short.MAX_VALUE)
                            .addComponent(txt_Matpel)
                            .addComponent(txt_ustad)
                            .addComponent(txt_santri)
                            .addComponent(txt_UTS)
                            .addComponent(txt_UAS)
                            .addComponent(txt_nilai))))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Hapus)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cari))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox_NISN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox_id_ustad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox_id_mapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_Matpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_ustad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_santri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_UTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_UAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambah)
                            .addComponent(btn_edit)
                            .addComponent(btn_reset)
                            .addComponent(btn_home)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Hapus)
                    .addComponent(txt_pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cari))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nilaiActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        String id_nilai = txt_pencarian.getText();
        Object[] baris = {"ID Nilai", "NISN", "ID Mapel", "ID Ustad", "UAS", "UTS"};
        DefaultTableModel tabmode = new DefaultTableModel(null, baris);
        table_nilai.setModel(tabmode);

        try {
            hasil = aa.CariData(Integer.parseInt(id_nilai));
            if (hasil.next()) {
                String id = hasil.getString("id_nilai");
                String nisn = hasil.getString("NISN");
                String idMatpel = hasil.getString("id_matpel");
                String idUstad = hasil.getString("id_ustad");
                String uas = hasil.getString("UAS");
                String uts = hasil.getString("UTS");
                String[] data = {id, nisn, idMatpel, idUstad, uas, uts};
                tabmode.addRow(data);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Data tidak ditemukan");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        if (txt_pencarian.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_pencarian.requestFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?", "Warning", 2) == JOptionPane.YES_OPTION) {
                String nisn = "";
                try {
                    aa.setId_nilai(Integer.parseInt(txt_pencarian.getText()));
                    aa.hapusData(aa.getId_nilai());
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                    tampil_database();
                    reset_text();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Data gagal dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pencarianActionPerformed

    private void txt_pencarianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_pencarianMouseClicked
        txt_pencarian.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pencarianMouseClicked

    private void jComboBox_NISNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_NISNActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_NISNActionPerformed

    private void txt_MatpelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MatpelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MatpelActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        dispose();
        Home home = new Home();
        home.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        if (txt_nilai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_nilai.requestFocus();
        } else if (txt_UTS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UTS belum diisi !");
            txt_UTS.requestFocus();
        } else if (txt_UAS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UAS belum diisi !");
            txt_UAS.requestFocus();
        } else {
            try {
                aa.setId_nilai(Integer.parseInt(txt_nilai.getText()));
                aa.setNISN(jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex()));
                aa.setId_matpel(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
                aa.setId_ustad(Integer.parseInt(jComboBox_id_ustad.getItemAt(jComboBox_id_ustad.getSelectedIndex())));
                aa.setUTS(Integer.parseInt(txt_UTS.getText()));
                aa.setUAS(Integer.parseInt(txt_UAS.getText()));
                aa.ubahData(aa.getId_nilai(), aa.getNISN(), aa.getId_matpel(), aa.getId_ustad(), aa.getUAS(), aa.getUTS());
                JOptionPane.showMessageDialog(null, "Data berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }              // TODO add your handling code here:
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        if (txt_nilai.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, ID Nilai belum diisi !");
            txt_nilai.requestFocus();
        } else if (txt_UTS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UTS belum diisi !");
            txt_UTS.requestFocus();
        } else if (txt_UAS.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Maaf, Nilai UAS belum diisi !");
            txt_UAS.requestFocus();
        } else {
            try {
                aa.setId_nilai(Integer.parseInt(txt_nilai.getText()));
                aa.setNISN(jComboBox_NISN.getItemAt(jComboBox_NISN.getSelectedIndex()));
                aa.setId_matpel(Integer.parseInt(jComboBox_id_mapel.getItemAt(jComboBox_id_mapel.getSelectedIndex())));
                aa.setId_ustad(Integer.parseInt(jComboBox_id_ustad.getItemAt(jComboBox_id_ustad.getSelectedIndex())));
                aa.setUTS(Integer.parseInt(txt_UTS.getText()));
                aa.setUAS(Integer.parseInt(txt_UAS.getText()));
                aa.simpanData(aa.getId_nilai(), aa.getNISN(), aa.getId_matpel(), aa.getId_ustad(), aa.getUAS(), aa.getUTS());
                JOptionPane.showMessageDialog(null, "Data berhasil tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                tampil_database();
                reset_text();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        tampil_database();
        reset_text();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JComboBox<String> jComboBox_NISN;
    private javax.swing.JComboBox<String> jComboBox_id_mapel;
    private javax.swing.JComboBox<String> jComboBox_id_ustad;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_nilai;
    private javax.swing.JTextField txt_Matpel;
    private javax.swing.JTextField txt_UAS;
    private javax.swing.JTextField txt_UTS;
    private javax.swing.JTextField txt_nilai;
    private javax.swing.JTextField txt_pencarian;
    private javax.swing.JTextField txt_santri;
    private javax.swing.JTextField txt_ustad;
    // End of variables declaration//GEN-END:variables
}
